/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package mortar.gui;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;

import javax.swing.*;

import com.fazecast.jSerialComm.SerialPort;
import com.formdev.flatlaf.FlatLightLaf;

import mortar.gui.map.LoadMapWindow;
import mortar.gui.map.MapWindow;

public class App extends JFrame {
    private static SerialPort serialPort;

    JDesktopPane desktop;

    MapWindow mapWnd;
    CommWindow commWnd;

    JMenuBar menuBar;
    JMenuItem fireMenuItem;

    public App() {
        setTitle("NERF Mortar Control Panel");

        int inset = 50;
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        setBounds(inset, inset,
                  screenSize.width  - inset*2,
                  screenSize.height - inset*2);
 

        desktop = new JDesktopPane();
        desktop.setBackground(Color.GRAY);

        var connectionDialog = new ConnectionDialog();
        connectionDialog.setVisible(true);
        desktop.add(connectionDialog);

        mapWnd = new MapWindow();
        mapWnd.setVisible(true);
        desktop.add(mapWnd);

        setContentPane(desktop);

        createMenu();
    }

    private void createMenu() {
        menuBar = new JMenuBar();

        var fileMenu = new JMenu("File");

        var loadMapBtn = new JMenuItem("Load Map", KeyEvent.VK_M);
        loadMapBtn.addActionListener(event -> {
            var wnd = new LoadMapWindow(mapWnd.mapView);
            wnd.setVisible(true);
            desktop.add(wnd);
            wnd.toFront();
        });
        fileMenu.add(loadMapBtn);

        fireMenuItem = new JMenuItem("Fire", KeyEvent.VK_ENTER);
        fireMenuItem.setEnabled(commWnd != null);
        fireMenuItem.addActionListener((event) -> {
            if(commWnd != null) commWnd.fire(mapWnd.getAim());
            else Dialogs.showError("No serial connection available", this.desktop);
        });
        fileMenu.add(fireMenuItem);
        menuBar.add(fileMenu);

        var viewMenu = new JMenu("View");
        var mapBtn = new JMenuItem("Map");
        mapBtn.addActionListener(event -> {
            if(mapWnd != null) {
                mapWnd.setVisible(true);
                if(!SwingUtilities.isDescendingFrom(mapWnd, desktop)) desktop.add(mapWnd);
                mapWnd.toFront();
            }
            else {
                mapWnd = new MapWindow();
                mapWnd.setVisible(true);
                desktop.add(mapWnd);
            }
        });
        viewMenu.add(mapBtn);
        menuBar.add(viewMenu);

        var helpMenu = new JMenu("Help");

        var aboutMenuItem = new JMenuItem("About");
        aboutMenuItem.addActionListener((event) -> {
            JOptionPane.showInternalMessageDialog(this.desktop, "NERF Mortar Control Panel \u00A9 2023 Aleks Rutins");
        });

        helpMenu.add(aboutMenuItem);
        menuBar.add(helpMenu);

        setJMenuBar(menuBar);
    }

    public static void main(String[] args) {
        System.setProperty("fazecast.jSerialComm.appid", "MORTAR_GUI");

        FlatLightLaf.setup();
        
        SwingUtilities.invokeLater(() -> {
            JFrame.setDefaultLookAndFeelDecorated(true);
            var app = new App();
            app.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            app.setVisible(true);
        });
    }
}
